### ISSUE TITLE
Error when agreeing to terms

### ISSUE THREAD

**Issue by Wizrad325** [legoandmars/SlimeModManager#9]
When I click "I agree" to the terms I just get an error that says:
Could not download versions list. Mods tab disabled. Please restart to try again.
The problem persists even after I restart the program, and I've tried redownloading the mod manager several times and I still face the same issue.

Also, If I sit on the error message for a few seconds, I get another error that says:
Could not load game versions, Mods tab will be unavailable. 
System.ArgumentNullException: Value cannot be null. 
Parameter name: source
     at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
     at ModAssistant.MainWindow.<LoadVersionsAsync>d__11.MoveNext()

**Comment by legoandmars** [comment]
Issue should be completely fixed in [1.3.1](https://github.com/legoandmars/SlimeModManager/releases/tag/1.3.1)
